global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "urbanzen_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Device Management Service
  - job_name: 'device-mgmt'
    static_configs:
      - targets: ['device-mgmt:8081']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Data Ingestion Service
  - job_name: 'data-ingestion'
    static_configs:
      - targets: ['data-ingestion:8082']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Analytics Service
  - job_name: 'analytics'
    static_configs:
      - targets: ['analytics:8083']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Notification Service
  - job_name: 'notification'
    static_configs:
      - targets: ['notification:8084']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # User Management Service
  - job_name: 'user-mgmt'
    static_configs:
      - targets: ['user-mgmt:8085']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Billing Service
  - job_name: 'billing'
    static_configs:
      - targets: ['billing:8086']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Reporting Service
  - job_name: 'reporting'
    static_configs:
      - targets: ['reporting:8087']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Infrastructure monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  - job_name: 'timescaledb'
    static_configs:
      - targets: ['timescaledb-exporter:9187']
    scrape_interval: 30s

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Blackbox exporter for endpoint monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://api-gateway:8080/health
        - http://admin-dashboard:3000
        - http://public-dashboard:3000
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115