name: urbanzen_citizen
description: UrbanZen Smart City Citizen Mobile Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  material_symbols_icons: ^4.2719.3
  cupertino_icons: ^1.0.2
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^12.1.3
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.3.4
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # Maps & Location
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geolocator: ^10.1.0
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.1.0
  path_provider: ^2.1.1
  
  # Charts & Visualization
  fl_chart: ^0.65.0
  
  # Image & Media
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  
  # Notifications
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.0.0
  
  # Security
  local_auth: ^2.1.7
  
  # Connectivity
  connectivity_plus: ^5.0.2
  
  # QR Code
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
