apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: urbanzen-prod
  labels:
    app: api-gateway
    component: backend
    tier: gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        component: backend
        tier: gateway
    spec:
      containers:
      - name: api-gateway
        image: ghcr.io/bhanukaranwal/urbanzen/api-gateway:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: PORT
          value: "8080"
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: postgres-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: cache-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: urbanzen-prod
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-mgmt
  namespace: urbanzen-prod
  labels:
    app: device-mgmt
    component: backend
    tier: service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: device-mgmt
  template:
    metadata:
      labels:
        app: device-mgmt
        component: backend
        tier: service
    spec:
      containers:
      - name: device-mgmt
        image: ghcr.io/bhanukaranwal/urbanzen/device-mgmt:latest
        ports:
        - containerPort: 8081
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: PORT
          value: "8081"
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: postgres-url
        - name: TIMESCALEDB_URL
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: timescaledb-url
        - name: MQTT_BROKER
          value: "tcp://mosquitto-service:1883"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: device-mgmt-service
  namespace: urbanzen-prod
  labels:
    app: device-mgmt
spec:
  selector:
    app: device-mgmt
  ports:
  - name: http
    port: 80
    targetPort: 8081
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: urbanzen-prod
  labels:
    app: analytics
    component: backend
    tier: service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
        component: backend
        tier: service
    spec:
      containers:
      - name: analytics
        image: ghcr.io/bhanukaranwal/urbanzen/analytics:latest
        ports:
        - containerPort: 8083
        env:
        - name: PORT
          value: "8083"
        - name: TIMESCALEDB_URL
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: timescaledb-url
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: mongodb-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: cache-secrets
              key: redis-url
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: urbanzen-prod
  labels:
    app: analytics
spec:
  selector:
    app: analytics
  ports:
  - name: http
    port: 80
    targetPort: 8083
    protocol: TCP
  type: ClusterIP